[package]
name = "maelstrom"
version = "0.1.1"
authors = ["Raphael Robert"]
edition = "2018"

[dependencies]
uuid = { version = "0.8", features = ["v4"] }
x25519-dalek = "^0.6"
ed25519-dalek = {git="https://github.com/dalek-cryptography/ed25519-dalek.git", branch="develop"}
libsecp256k1 = "^0.3"
aead = "^0.2"
chacha20poly1305 = "^0.3"
aes-gcm = "^0.3"
hmac = "^0.7"
sha2 = "^0.8"
rand = "^0.7"
zeroize = "^1.1"
byteorder = "^1.3"

[dev-dependencies]
criterion = "^0.2"

[[bench]]
name = "benchmark"
harness = false