[package]
name = "maelstrom"
version = "0.2.0"
authors = ["Raphael Robert"]
edition = "2018"

[dependencies]
uuid = { version = "0.8", features = ["v4"] }
rayon = "^1.3"
rand = "^0.7"
zeroize = "^1.1"
byteorder = "^1.3"
hpke = {git = "https://github.com/franziskuskiefer/hpke-rs", branch = "master"}
evercrypt = {git = "https://github.com/franziskuskiefer/evercrypt-rust", branch = "master"}

[dev-dependencies]
criterion = "^0.2"

[[bench]]
name = "benchmark"
harness = false
